version: '3'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: rabbit
    ports:
      # AMQ Protocol Port
      - '30425:30425'
      # RMQ Management UI Port
      - '15673:15673'
    environment:
     - VHOST=rmq-docker-broker
  rmq_lab:
    build: tech_lab_build
    depends_on:
      - rabbitmq
    ports:
      #Jupyter notebook port 
      - '8889:8889'
    volumes:
      - ./:/app
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'    
